// USER
export const GET_USER = "GET_USER";

// AUTH
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SET_TOKEN = "SET_TOKEN";

// GENERAL
export const SET_GENERAL = "SET_GENERAL";
export const SAVE_GENERAL = "SAVE_GENERAL";

// CONTACTS
export const SET_CONTACTS = "SET_CONTACTS";
export const SAVE_CONTACTS = "SAVE_CONTACTS";

// SKILLS
export const ADD_SKILLS_CATEGORY = "ADD_SKILLS_CATEGORY";
export const UPDATE_SKILLS_CATEGORY_NAME = "UPDATE_SKILLS_CATEGORY_NAME";
export const MOVE_SKILLS_CATEGORY = "MOVE_SKILLS_CATEGORY";
export const DELETE_SKILLS_CATEGORY = "DELETE_SKILLS_CATEGORY";
export const ADD_SKILLS_CATEGORY_TECHNOLOGY = "ADD_SKILLS_CATEGORY_TECHNOLOGY";
export const UPDATE_SKILLS_CATEGORY_TECHNOLOGY = "UPDATE_SKILLS_CATEGORY_TECHNOLOGY";
export const MOVE_SKILLS_CATEGORY_TECHNOLOGY = "MOVE_SKILLS_CATEGORY_TECHNOLOGY";
export const DELETE_SKILLS_CATEGORY_TECHNOLOGY = "DELETE_SKILLS_CATEGORY_TECHNOLOGY";
export const SAVE_SKILLS = "SAVE_SKILLS";

// EXPERIENCES
export const SET_EXPERIENCES = "SET_EXPERIENCES";
export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const MOVE_EXPERIENCE = "MOVE_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";

// EDUCATION
export const SET_EDUCATIONS = "SET_EDUCATIONS";
export const CREATE_EDUCATION = "CREATE_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const MOVE_EDUCATION = "MOVE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";

// LANGUAGES
export const SET_LANGUAGES = "SET_LANGUAGES";
export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const MOVE_LANGUAGE = "MOVE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

// PROJECTS
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const MOVE_PROJECT = "MOVE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const ADD_PROJECT_TAG = "ADD_PROJECT_TAG";
export const UPDATE_PROJECT_TAG = "UPDATE_PROJECT_TAG";
export const MOVE_PROJECT_TAG = "MOVE_PROJECT_TAG";
export const DELETE_PROJECT_TAG = "DELETE_PROJECT_TAG";
export const SAVE_PROJECTS = "SAVE_PROJECTS";
export const SAVE_PROJECT_SCREENSHOT = "SAVE_PROJECT_SCREENSHOT";
export const DELETE_PROJECT_SCREENSHOT = "DELETE_PROJECT_SCREENSHOT";

// RESUME
export const UPDATE_RESUME = "UPDATE_RESUME";
export const SAVE_RESUME = "SAVE_RESUME";
export const DELETE_RESUME = "DELETE_RESUME";

// USER INTERFACE
export const ADJUST_REQUESTS_QUANTITY = "ADJUST_REQUESTS_QUANTITY";
