// AUTH
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SET_TOKEN = "SET_TOKEN";

// GENERAL
export const SET_GENERAL = "SET_GENERAL";
export const SAVE_GENERAL = "SAVE_GENERAL";

// CONTACTS
export const SET_CONTACTS = "SET_CONTACTS";
export const SAVE_CONTACTS = "SAVE_CONTACTS";

// SKILLS
export const ADD_SKILLS_CATEGORY = "ADD_SKILLS_CATEGORY";
export const UPDATE_SKILLS_CATEGORY_NAME = "UPDATE_SKILLS_CATEGORY_NAME";
export const MOVE_SKILLS_CATEGORY = "MOVE_SKILLS_CATEGORY";
export const DELETE_SKILLS_CATEGORY = "DELETE_SKILLS_CATEGORY";
export const ADD_SKILLS_CATEGORY_TECHNOLOGY = "ADD_SKILLS_CATEGORY_TECHNOLOGY";
export const UPDATE_SKILLS_CATEGORY_TECHNOLOGY = "UPDATE_SKILLS_CATEGORY_TECHNOLOGY";
export const MOVE_SKILLS_CATEGORY_TECHNOLOGY = "MOVE_SKILLS_CATEGORY_TECHNOLOGY";
export const DELETE_SKILLS_CATEGORY_TECHNOLOGY = "DELETE_SKILLS_CATEGORY_TECHNOLOGY";
export const SAVE_SKILLS = "SAVE_SKILLS";

// EXPERIENCES
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const MOVE_EXPERIENCE = "MOVE_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const SAVE_EXPERIENCES = "SAVE_EXPERIENCES";

// EDUCATION
export const SET_EDUCATION = "SET_EDUCATION";
export const SAVE_EDUCATION = "SAVE_EDUCATION";

// LANGUAGES
export const SET_LANGUAGE = "SET_LANGUAGE";
export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const MOVE_LANGUAGE = "MOVE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";
export const SAVE_LANGUAGES = "SAVE_LANGUAGES";

// PROJECTS
export const GET_PROJECTS = "GET_PROJECTS";
